# Simulation test 

# This approach to simulation-estimation is called "self-testing," where the same model
# is used to generate the data and fitting the model to data. This approach
# should generate exact parameter estimates in the case where data are generated with no
# simulated observation errors.

source("R/helper.r") 

main_dir <- getwd()#"S:\\Region1Shared-DCF\\Research\\Herring-Dive Fisheries\\Herring\\ADMB Rudd Workshop 2018\\AlaskaHerring"
proj_dir <- file.path(main_dir, "HER")
setwd(proj_dir)


files <- list.files(file.path(proj_dir))

## find tpl name (generalizes code across directories)
tpl <- file.path(proj_dir, files[which(grepl(".tpl", files))])
name <- strsplit(files[grepl("tpl",files)],".tpl")[[1]][1]

# Step-by-step instructions from S. Martell's Technical Doc. For this
# simulation, experiment, the Sitka herring stock will be used. 

# 1) First, fit the model to the Sitka data to obtain the parameter file (.par)
setup_admb()
compile_admb(name, verbose = TRUE)
run_admb(name, verbose = TRUE)

# 2) Make a copy of the .par file. It will serve as the parameter input file for
# the simulation (.pin)
par <- file.path(proj_dir, files[which(grepl(".par", files))])
pin <- paste0(proj_dir, "/", name, ".pin")
file.copy(from = par, to = pin, overwrite = TRUE)	

# 3) Next run the model using the -sim flag with a random number seed. The
# random seed is for the random numbers in the observation errors. Create
# subdirectories for each simulation result to look at the range of variability
# generated by the observation error.

# Create paths for the files needed to run each simulation
dat <- file.path(proj_dir, files[which(grepl(".dat", files))]) 
ctl <- file.path(proj_dir, files[which(grepl(".ctl", files))])
exe <- paste0(name,".exe")
file.exists(exe) # Should be true

# std file (for checking model convergence in loop)
std <- paste0(name,".std")
check_converge <- list()

## loop over simulations 
sims <- 1:5
rundir <- file.path(proj_dir, "simulations")
dir.create("simulations", showWarnings = FALSE)

for(i in 1:length(sims)){
  
  simdir <- file.path(rundir, paste0("sim_", sims[i]))
  dir.create(simdir, showWarnings = FALSE)
  setwd(simdir)
  
  # copy TPL to run directory
  file.copy(from = tpl, to = simdir, overwrite = TRUE)	
  
  # copy exe
  file.copy(from = file.path(proj_dir, exe), to = simdir, overwrite = TRUE)	
  
  # copy pin
  file.copy(from = file.path(proj_dir, pin), to = simdir, overwrite = TRUE)	
  
  # copy data files
  file.copy(from = dat[1], to = simdir, overwrite = TRUE)	
  file.copy(from = dat[2], to = simdir, overwrite = TRUE)	
  
  # copy ctl file
  file.copy(from = ctl, to = simdir, overwrite = TRUE)	
  
  # remove pre-existing std file if it exists
  if (file.exists(std)) {file.remove(std, showWarnings = FALSE)}
  
  # run admb, set seed at retro value
  run_admb(name, extra.args=paste("-sim", sims[i]), verbose = TRUE)
  
  # check for convergence (1 = converge, 0 = not converged)
  if (file.exists(std)) {
    check_converge[[i]] <- 1
  } else {check_converge[[i]] <- 0 }
  
}

# Check convergence (1 = converged, 0 = not)
check_converge

# The test should result in estimates that fall within the 95% confidence
# interval that was used to generate the data.


# In progress: modifying Steve's code
read_output <- function(d) {
  if(file.exists(file.path(d, paste0(name, ".cor")))){
    return(read_admb(file.path(d, name)));
  }
  else {
    return(NULL)
  }
}

dn <- dir(path = rundir, pattern = "sim_[[:digit:]]", full.names = TRUE)
sim_out <- lapply(dn, read_output)

# If you want to save all the output
# nf <- paste0("sims",".Rdata")
# save(sim_out, file = nf)

# Create Data Frame of Parameter Estimates.
t1 <- lapply(sim_out,'[[','fit')
t2 <- lapply(t1,'[[','est')
df <- do.call(rbind,t2)

theta <- sim_out[[1]]$theta_ival

# boxplot(t(log2(t(df[,1:5])/theta)),ylim=c(-1,1))

# A nicer boxplot.
ndf   <- df[,1:5]
colnames(ndf) <- c("M", "Ri", "Rbar", "Ro", "Kappa")
err   <- as.data.frame(t((t(ndf)-theta)/theta)*100)

ggplot(gather(err),aes(key,value)) + geom_boxplot() + 
  ylim(c(-100, 100)) +
  labs(x="\nParameter",y="\nRelative Error (%)")

plot.all.simulations <- function(D) {
  
  # get index for simulation directories
  id <- grep("sim_out",sapply(D,"[[","Model"))
  
  # select only simulation model runs
  T  <- D[-id]
  S  <- D[id]
  
  
  p.sims <- NULL
  p.sims$label <- D$Model
  
  S <- sim_out
  # Spawning stock biomass 
  yrs <- S[[1]]$year
  ssb <- cbind(Year=yrs,as.data.frame(sapply(S,"[[","ssb"))) %>% 
    gather(Simulation,SSB,-Year)
  sitka <- cbind(Year=yrs,as.data.frame(sapply(T,"[[","ssb"))) %>%
    gather(Simulation,SSB,-Year)
  
  print(head(ssb))
  p.sims$ssb <- ggplot(ssb,aes(Year,SSB,color=factor(Simulation))) +
  							geom_line(alpha=0.8) +
  							geom_line(aes(Year,SSB),alpha=0.3,size=1.5,data=sitka,color="black") +
  							labs(x="Year",y="Spawning stock biomass (mt)",color="Simulation")
  
  p.sims$ssb <- plot.ssb(T[[1]]) + 
    geom_line(aes(Year,SSB,color=factor(Simulation)),alpha=0.5,size=0.5,data=ssb) + 
    labs(x="Year",y="Spawning stock biomass (mt)",color="Simulation")
  
  
  # Fishing mortality rates
  fft <- cbind(Year=yrs,as.data.frame(sapply(S,"[[","ft"))) %>%
    gather(Simulation,fft,-Year)
  # S
  p.sims$ft <- plot.ft(T[[1]]) +
    geom_line(data=fft,aes(Year,fft,color=factor(Simulation)),alpha=0.5,size=0.5)+ 
    labs(x="Year",y="Instantaneous fishing mortality rate")
  
  # Box plots for theta
  nm <- c("M","Rinit","Rbar","Ro","Reck","SigmaR")
  theta.pred <- sapply(D,"[[","theta")
  theta.true <- sapply(D,"[[","theta_ival")
  theta.ln2r <- t(log(theta.true/theta.pred,base=2)[,-1])
  colnames(theta.ln2r) <- nm
  
  p.sims$theta <- boxplot(theta.ln2r,ylim=c(-1,1))
  
  return(p.sims)
}

simulation.plots <- plot.all.simulations(M)
